kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "optimizely-agent.fullname" . }}
  labels:
    {{- include "optimizely-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl .Values.config . | nindent 4 }}
